# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ViewText.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ViewExe(object):
    def setupUi(self, ViewExe):
        ViewExe.setObjectName("ViewExe")
        ViewExe.resize(469, 489)
        self.gridLayout = QtWidgets.QGridLayout(ViewExe)
        self.gridLayout.setObjectName("gridLayout")
        self.TB_Exe = QtWidgets.QTextBrowser(ViewExe)
        self.TB_Exe.setObjectName("TB_Exe")
        self.gridLayout.addWidget(self.TB_Exe, 0, 0, 1, 3)
        self.PB_Ok = QtWidgets.QPushButton(ViewExe)
        self.PB_Ok.setObjectName("PB_Ok")
        self.gridLayout.addWidget(self.PB_Ok, 1, 0, 1, 1)
        self.PB_Cancel = QtWidgets.QPushButton(ViewExe)
        self.PB_Cancel.setObjectName("PB_Cancel")
        self.gridLayout.addWidget(self.PB_Cancel, 1, 1, 1, 1)
        self.PB_Save = QtWidgets.QPushButton(ViewExe)
        self.PB_Save.setObjectName("PB_Save")
        self.gridLayout.addWidget(self.PB_Save, 1, 2, 1, 1)

        self.retranslateUi(ViewExe)
        QtCore.QMetaObject.connectSlotsByName(ViewExe)

    def retranslateUi(self, ViewExe):
        _translate = QtCore.QCoreApplication.translate
        ViewExe.setWindowTitle(_translate("ViewExe", "Run MMG"))
        self.PB_Ok.setText(_translate("ViewExe", "Ok"))
        self.PB_Cancel.setText(_translate("ViewExe", "Cancel"))
        self.PB_Save.setText(_translate("ViewExe", "Save log"))
